### PR TITLE
Fix issue with notification icon

### LINKED ISSUE #14: Frequent crashes on Android 7.1
I use version 1.0.5 from F-droid on Android 7.1 on a Samsung phone. I get the OS crash popup almost once a day.

```
FATAL EXCEPTION: main
Process: ch.abertschi.waterme.water_me, PID: 30723
android.app.RemoteServiceException: Bad notification posted from package ch.abertschi.waterme.water_me: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=ch.abertschi.waterme.water_me id=0x7f090000) visible user=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1832)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

### PR DESCRIPTION
**Pull request by abertschi**
Fixes #14 

@opk12 could you please test these changes on your device. The issue seems to only occur on older versions of android.

### CODE REVIEW

**Comment by abertschi** [comment]
Download the apk of the build of this pull request:
- Open Build APK github runner shown above, scroll down to artifacts, and download the apk. Be aware that github zips the artifact again, so you first have to unzip the downloaded artifact to receive the apk.

**Comment by abertschi** [comment]
image

**Comment by opk12** [comment]
Thank you for the very quick reply! Sadly, the phone's owner won't let me install outside the F-droid repo, so I cannot test the package.

**Comment by opk12** [comment]
@abertschi 1.0.6 fixes it! Many thanks!

**Pull request merged**
