### PR TITLE
Support web platform

### PR DESCRIPTION
**Pull request by cyberme0w**
Hey! PR related to #20 and #2.

Since some people were requesting other platforms, I've gone ahead and added some form of support for them. `windows`, `linux` and `web` should now work, however there is a slight caveat.

There are currently two issues with these platforms:
1. `web` uses a different abstraction for I/O, which you had already mentioned in #20.
2. `linux` builds don't seem to support cameras - at least the respective Flutter issue is still marked as `open`. 
As a workaround, I've disabled the camera/pictures unless the build is `android` or `ios`.

As an example, the `linux` build currently looks like this (don't mind the yellow margin - that has to do with my window manager):
<p align="center">

</p>

The Android/iOS builds still display and support the pictures button.

Please let me know if this is something you'd consider adding, or if you'd like to see any changes or improvements before.

### CODE REVIEW

**Comment by cyberme0w** [comment]
Focusing on the web target makes sense to me, too. I'll see if I can take a look at how Flutter handles responsive design and I/O for the web target. I can post some updates in #2 when I get around to it.

Cheers!

**Comment by cyberme0w** [comment]
There might be another way to handle images without having to do some web-specific shenanigans (I might have underestimated the state of Flutter's web I/O a bit ^^).

I'm not sure about performance, but it should be possible to base64-encode the images and then store them to the shared preferences as strings. Since these should behave the same regardless of platform, it would allow for native Android/iOS builds as well as the web build.

**Comment by abertschi** [comment]
I think the easiest approach is just to add a proxy wherever we have these issues. The proxy function queries the platform

https://stackoverflow.com/questions/45924474/how-do-you-detect-the-host-platform-from-dart-code

and then we have a different implementation for web/ android.

**Comment by abertschi** [comment]
> I'm not sure about performance, but it should be possible to base64-encode the images and then store them to the shared preferences as strings. 

I would just use the current implementation as-is for android. You can serialize images into base64 if you want for web and use local storage to store it. If that's the best solution you found im ok with this.

**Comment by cyberme0w** [comment]
Hey there!

I managed to get the web implementation working with pictures:

left: Brave (running as a PWA)
right: Firefox

It works by storing the image captured by the camera as bytes (`Uint8List`) instead of an actual file (`XFile`). This way, the values can be passed around without needing to store anything locally. Those bytes can then be displayed as an image by using `MemoryImage` (instead of `FileImage`).

Storing the images to JSON is also still possible, however now instead of saving the file paths, a Base64 encoded String of the image's bytes is used. This would mean that any old `plant.image`s (file paths) would need to be converted to the base64 string.

This implementation also works on Android.

Since the images get stored in the `sharedPreferences` (android) / browser cookies (web), storage permissions wouldn't be required anymore.

I'll go ahead and commit what I have now, however it still needs a bit of cleanup, as well as deciding if the proxies are necessary, since this version works on all platforms. Personally I think it would be better to keep things the same everywhere, but it's your call :)

Cheers!

**Comment by abertschi** [comment]
> I'll go ahead and commit what I have now, however it still needs a bit of cleanup, as well as deciding if the proxies are necessary, since this version works on all platforms. Personally I think it would be better to keep things the same everywhere, but it's your call :)

Let us discuss this. Here are some pro/ contra of this approach.

Pro:
- Android version does not need storage permissions (at least not for add of a plant)
- Same code for Android+Web

Contra:
- Proprietary format (binary blob), not easily accessible outside of app, no encoding hints are stored.
- Json is bloated with a binary dump

The json export in any case requires storage permission. Web support (mobile) requires some platform specific code to handle notifications, background tasks, and home screen integration.

**Pull request closed without merging**
